server:
  port: 8081
  servlet:
    context-path: /sms-service

twilio:
  accountSid: #############################
  authToken: #############################
  phone: #############################

rabbitmq-otp:
  queue: otp_code_sms_queue
  exchange: otp_code_sms_exchange
  routingKey: otp_code_sms_routing_key
