server:
  port: 8081
  servlet:
    context-path: /sms-service

twilio:
  accountSid: ACeae636ec6515ae3a8e83db3627ada798
  authToken: 5d3ded14890b3ee4af09d25be03d9afe
  phone: +14706844686

rabbitmq-otp:
  queue: otp_code_sms_queue
  exchange: otp_code_sms_exchange
  routingKey: otp_code_sms_routing_key
